package ui;

import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.DefaultListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import utilities.Tools;

/**
 *
 * @author Dan
 */
public class NexusRepoUI extends javax.swing.JFrame implements ActionListener,
		ListSelectionListener {
	DefaultListModel scripts = new DefaultListModel();
	DefaultListModel myscripts = new DefaultListModel();
	DefaultListModel myinfo = new DefaultListModel();

	Image noScript = Tools.getLocalImage("Data/Images/no_script.png");

	boolean refresh = true;

	/**
	 * Creates new form NexusRepo
	 */
	public NexusRepoUI() {
		initComponents();
		this.setTitle("Nexus Script Repo");
		this.setIconImage(TronicUI.T);
		this.setScriptImg(noScript);
		this.setResizable(false);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		TABS = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		SEARCHITEM = new javax.swing.JTextField();
		SKILLCATEGORY = new javax.swing.JComboBox();
		jScrollPane1 = new javax.swing.JScrollPane();
		SCRIPTLIST = new javax.swing.JList();
		SCRIPT_IMG = new ScriptImagePanel(this.noScript);
		ADDSCRIPT = new NexusButton("Add Script");
		jPanel2 = new javax.swing.JPanel();
		jScrollPane2 = new javax.swing.JScrollPane();
		MYSCRIPTS = new javax.swing.JList();
		REMOVEBUTTON = new NexusButton("Remove");
		jScrollPane3 = new javax.swing.JScrollPane();
		ACCOUNTINFO = new javax.swing.JList();

		ADDSCRIPT.addActionListener(this);
		REMOVEBUTTON.addActionListener(this);
		SEARCHITEM.addActionListener(this);
		SCRIPTLIST.addListSelectionListener(this);

		REMOVEBUTTON.setFadeInColor(new Color(255, 0, 0, 200));
		ADDSCRIPT.setFadeInColor(new Color(0, 255, 0, 200));

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		SKILLCATEGORY.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "All Scripts", "Fighters", "Prayer", "Magic",
						"Runecrafting", "Crafting", "Mining", "Smithing",
						"Fishing", "Cooking", "Firemaking", "Woodcutting",
						"Agility", "Herblore", "Theiving", "Fletching",
						"Slayer", "Construction", "Hunter", "Money Making",
						"Misc" }));

		jScrollPane1.setViewportView(SCRIPTLIST);

		SCRIPT_IMG.setBackground(new java.awt.Color(102, 102, 102));

		javax.swing.GroupLayout SCRIPT_IMGLayout = new javax.swing.GroupLayout(
				SCRIPT_IMG);
		SCRIPT_IMG.setLayout(SCRIPT_IMGLayout);
		SCRIPT_IMGLayout.setHorizontalGroup(SCRIPT_IMGLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGap(0, 0, Short.MAX_VALUE));
		SCRIPT_IMGLayout.setVerticalGroup(SCRIPT_IMGLayout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 576,
				Short.MAX_VALUE));

		ADDSCRIPT.setText("Add Script");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																SEARCHITEM)
														.addComponent(
																SKILLCATEGORY,
																0, 309,
																Short.MAX_VALUE)
														.addComponent(
																jScrollPane1))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																SCRIPT_IMG,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																ADDSCRIPT,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																753,
																Short.MAX_VALUE))
										.addContainerGap()));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				SCRIPT_IMG,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				ADDSCRIPT,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				72,
																				Short.MAX_VALUE))
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				SEARCHITEM,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				SKILLCATEGORY,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jScrollPane1)))
										.addContainerGap()));

		TABS.addTab("Nexus Script Repo", jPanel1);

		jScrollPane2.setViewportView(MYSCRIPTS);

		REMOVEBUTTON.setText("Remove");

		jScrollPane3.setViewportView(ACCOUNTINFO);

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																jScrollPane2)
														.addComponent(
																REMOVEBUTTON,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																308,
																Short.MAX_VALUE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												750, Short.MAX_VALUE)
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel2Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				547,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				REMOVEBUTTON,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				101,
																				Short.MAX_VALUE))
														.addComponent(
																jScrollPane3))
										.addContainerGap()));

		TABS.addTab("My Account", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(TABS));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(TABS));

		pack();
	}// </editor-fold>

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(NexusRepoUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(NexusRepoUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(NexusRepoUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(NexusRepoUI.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new NexusRepoUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	public static javax.swing.JList ACCOUNTINFO;
	public static NexusButton ADDSCRIPT;
	public static javax.swing.JList MYSCRIPTS;
	public static NexusButton REMOVEBUTTON;
	public static ScriptImagePanel SCRIPT_IMG;
	public static javax.swing.JList SCRIPTLIST;
	public static javax.swing.JTextField SEARCHITEM;
	public static javax.swing.JComboBox SKILLCATEGORY;
	public static javax.swing.JTabbedPane TABS;
	public static javax.swing.JPanel jPanel1;
	public static javax.swing.JPanel jPanel2;
	public static javax.swing.JScrollPane jScrollPane1;
	public static javax.swing.JScrollPane jScrollPane2;
	public static javax.swing.JScrollPane jScrollPane3;

	// End of variables declaration
	@Override
	public void actionPerformed(ActionEvent e) {
		switch (e.getActionCommand()) {
		case "Add Script":
			if (SCRIPTLIST.getSelectedValue() != null)
				this.addScriptToAccount(SCRIPTLIST.getSelectedValue()
						.toString());
			break;
		case "Remove":
			if (MYSCRIPTS.getSelectedValue() != null)
				this.removeScriptFromAccount(MYSCRIPTS.getSelectedValue()
						.toString());
			break;
		default:
			if (SEARCHITEM.getText() != null)
				this.filterScriptList(SEARCHITEM.getText());
		}
	}

	public void filterScriptList(String search) {
		Tools.log("Searching For: " + search + " in skill: "
				+ SKILLCATEGORY.getSelectedItem().toString());
	}

	public void removeScriptFromAccount(String script) {
		Tools.log("Removing Script: " + script);
	}

	public void addScriptToAccount(String script) {
		Tools.log("Adding Script: " + script);
	}

	@Override
	public void valueChanged(ListSelectionEvent e) {
		if (SCRIPTLIST.getSelectedValue() != null) {

		} else {
			this.setScriptImg(noScript);
			SCRIPT_IMG.repaint();
		}
	}

	public void setScriptImg(Image image) {
		SCRIPT_IMG.setImage(image);
	}

}
